<template>
    <g-breadcrumb>
        <g-breadcrumb-item>Home</g-breadcrumb-item>
        <g-breadcrumb-item>Channel</g-breadcrumb-item>
        <g-breadcrumb-item>About</g-breadcrumb-item>
    </g-breadcrumb>
    <g-breadcrumb>
        <g-breadcrumb-item>Home</g-breadcrumb-item>
        <g-breadcrumb-item>Channel</g-breadcrumb-item>
        <g-breadcrumb-item>About</g-breadcrumb-item>
        <g-breadcrumb-item>Detail</g-breadcrumb-item>
        <g-breadcrumb-item>More</g-breadcrumb-item>
    </g-breadcrumb>
</template>